#Install on fresh system(Ankit Specific)


sudo apt-get -y install firefox
sudo apt-get -y install xchat
sudo apt-get -y install xfonts-terminus
sudo apt-get -y install mercurial
sudo apt-get -y install geany
sudo apt-get -y install python3
sudo apt-get -y install gnome-mplayer
#sudo apt-get -y install k3b
sudo apt-get -y install pidgin
sudo apt-get -y install transmission
sudo apt-get -y install gimp
sudo apt-get -y install gcolor2
sudo apt-get -y install vlc
sudo apt-get -y install xvidcap
sudo apt-get -y install epdfview
sudo apt-get -y install evince
#sudo apt-get -y install kchmviewer
#sudo apt-get -y install xchm
#sudo apt-get -y install lubuntu-restricted-extras
#sudo apt-get -y install lubuntu-restricted-addons
#sudo apt-get -y install kolourpaint
sudo apt-get -y install pdfedit
#sudo apt-get -y install sgt-puzzles
#sudo apt-get -y install chromium-browser
sudo apt-get -y install wget
sudo apt-get -y install libreoffice
#sudo apt-get -y install flpsed
sudo apt-get -y install dia
#sudo apt-get -y install avidemux
sudo apt-get -y install audacity
sudo apt-get -y install inkscape
sudo apt-get -y install midori
sudo apt-get -y install ekiga
#sudo apt-get -y install ktouch
sudo apt-get -y install klavoro
sudo apt-get -y install octave3.2
sudo apt-get -y install gnuplot
sudo apt-get -y install gcc
sudo apt-get -y install p7zip
sudo apt-get -y install nethogs
sudo apt-get -y install dkms
sudo apt-get -y install subversion
sudo apt-get -y install git
sudo apt-get -y install alsamixergui
sudo apt-get -y install skype
sudo apt-get -y install catfish
#sudo apt-get -y install recordmydesktop
sudo apt-get -y install geany-plugins
sudo apt-get -y install p7zip-full
#sudo apt-get -y install wine
#sudo apt-get -y install lyx
sudo apt-get -y install ipython
#sudo apt-get -y install suckless-tools
#sudo apt-get -y install dmenu
#sudo apt-get -y install flpsed
#sudo apt-get -y install pdfedit
sudo apt-get -y install ttf-mscorefonts-installer
sudo apt-get -y install xournal
sudo apt-get -y install bzr
sudo apt-get -y install cmake
#sudo apt-get -y install xdot
sudo apt-get -y install g++
#sudo apt-get -y install bpython
sudo apt-get -y install checkinstall
#sudo apt-get -y install bzrtools
#sudo apt-get -y install bzr-rebase
sudo apt-get -y install gparted
sudo apt-get -y install build-essential
sudo apt-get -y install preload
